# Generated by Django 5.1.3 on 2024-11-12 13:55

import django.contrib.postgres.fields
import django.db.models.deletion
import online_security.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('importance', models.CharField(choices=[('critical', 'Critical'), ('recommended', 'Recommended'), ('optional', 'Optional')], max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
            bases=(online_security.models.OrderedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('importance', models.CharField(choices=[('critical', 'Critical'), ('recommended', 'Recommended'), ('optional', 'Optional')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='recommendations', to='online_security.category')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            bases=(online_security.models.OrderedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo_icon', models.ImageField(blank=True, null=True, upload_to='solution_logos/')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('practice', 'Practice')], max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_duration', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('lifetime', 'Lifetime'), ('one-time', 'One-time Purchase')], max_length=20, null=True)),
                ('implementation_difficulty', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('learning_curve', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('implementation_time', models.CharField(blank=True, max_length=100, null=True)),
                ('supported_platforms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None, validators=[online_security.models.validate_platforms])),
                ('download_link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('recommendations', models.ManyToManyField(related_name='solutions', to='online_security.recommendation')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            bases=(online_security.models.OrderedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_time', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='online_security.solution')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            bases=(online_security.models.OrderedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TutorialStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='tutorial_images/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='online_security.tutorial')),
            ],
            options={
                'ordering': ['tutorial', 'order'],
                'unique_together': {('tutorial', 'order')},
            },
            bases=(online_security.models.OrderedModelMixin, models.Model),
        ),
    ]
