# Generated by Django 5.1.3 on 2024-11-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_security', '0004_solution_implementation_time_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='strengths',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='weaknesses',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='cost_duration',
            field=models.CharField(blank=True, choices=[('month', 'Month'), ('year', 'Year'), ('one_time', 'One-Time')], max_length=20, null=True),
        ),
    ]
