# Generated by Django 5.1.3 on 2024-11-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_security', '0005_solution_strengths_solution_weaknesses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
