# Generated by Django 5.1.3 on 2024-11-13 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_hashedemail_remove_user_has_logged_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashed_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.hashedemail'),
        ),
    ]
