# Generated by Django 5.1.3 on 2024-11-16 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('importance', models.CharField(choices=[('critical', 'Critical - Required for survival'), ('recommended', 'Recommended - Significantly improves chances'), ('optional', 'Optional - Additional support')], max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('uses', models.TextField()),
                ('importance', models.CharField(choices=[('critical', 'Critical'), ('recommended', 'Recommended'), ('optional', 'Optional')], max_length=20)),
                ('weight_note', models.CharField(blank=True, help_text="e.g. 'Light', 'Heavy', 'One per person'", max_length=100)),
                ('special_considerations', models.TextField(blank=True, help_text='Notes about children, elderly, pets, etc.')),
                ('order', models.IntegerField(default=0)),
                ('alternatives', models.ManyToManyField(blank=True, to='pack_planner.item')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pack_planner.category')),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('last_verified', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_products', to='pack_planner.item')),
            ],
        ),
    ]
