# Generated by Django 5.1.3 on 2024-11-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'permissions': [('pack_planner_data_upload_permission', 'Can upload pack planning data')], 'verbose_name_plural': 'categories'},
        ),
    ]
