# Generated by Django 5.1.3 on 2024-11-17 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_planner', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='for_adults',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='for_bicycle',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='for_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='for_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='for_elderly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='for_on_foot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='for_pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='for_public_transit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='for_vehicle',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='importance',
            field=models.CharField(choices=[('critical', 'Critical'), ('recommended', 'Recommended'), ('optional', 'Optional')], max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pack_planner.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='special_considerations',
            field=models.TextField(blank=True, help_text='Special concerns, regulations, etc.'),
        ),
    ]
