# Generated by Django 5.1.3 on 2024-11-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_planner', '0003_item_for_adults_item_for_bicycle_item_for_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='conditional_applicability',
            field=models.BooleanField(default=False),
        ),
    ]
