# Generated by Django 5.1.3 on 2024-11-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_planner', '0004_item_conditional_applicability'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='go_bag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='seventy_two_hr_bag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='go_bag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='seventy_two_hr_bag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='go_bag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seventy_two_hr_bag',
            field=models.BooleanField(default=True),
        ),
    ]
