# Generated by Django 5.1.3 on 2024-11-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack_planner', '0005_category_go_bag_category_seventy_two_hr_bag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='go_bag',
        ),
        migrations.RemoveField(
            model_name='item',
            name='go_bag',
        ),
        migrations.RemoveField(
            model_name='product',
            name='go_bag',
        ),
    ]
