# Generated by Django 5.1.3 on 2024-11-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_planner', '0006_remove_category_go_bag_remove_item_go_bag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='go_bag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='for_cats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='for_dogs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='for_small_animals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='go_bag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='go_bag',
            field=models.BooleanField(default=True),
        ),
    ]
