# Generated by Django 5.1.3 on 2024-11-20 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relocation_planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costofliving',
            name='country',
        ),
        migrations.RemoveField(
            model_name='costofliving',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='costofliving',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='edithistory',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='edithistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='edithistory',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='healthcareinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='healthcareinfo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='healthcareinfo',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='propertycost',
            name='country',
        ),
        migrations.RemoveField(
            model_name='propertycost',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='propertycost',
            name='last_modified_by',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rating',
            name='country',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='relocationprocess',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='relocationprocess',
            name='country',
        ),
        migrations.RemoveField(
            model_name='relocationprocess',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='relocationprocess',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='resourcelink',
            name='country',
        ),
        migrations.RemoveField(
            model_name='resourcelink',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='resourcelink',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='userexperience',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userexperience',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userexperience',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='userexperience',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='visatype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='country',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='visatype',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='visarequirement',
            name='visa_type',
        ),
        migrations.RemoveField(
            model_name='country',
            name='avg_cost_of_living',
        ),
        migrations.RemoveField(
            model_name='country',
            name='avg_house_cost',
        ),
        migrations.RemoveField(
            model_name='country',
            name='avg_rent_cost',
        ),
        migrations.RemoveField(
            model_name='country',
            name='capital_city',
        ),
        migrations.RemoveField(
            model_name='country',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='country',
            name='official_languages',
        ),
        migrations.RemoveField(
            model_name='country',
            name='population',
        ),
        migrations.RemoveField(
            model_name='country',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='petrelocationrequirement',
            name='country',
        ),
        migrations.RemoveField(
            model_name='petrelocationrequirement',
            name='documentation_required',
        ),
        migrations.RemoveField(
            model_name='petrelocationrequirement',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='petrelocationrequirement',
            name='pet_type',
        ),
        migrations.RemoveField(
            model_name='petrelocationrequirement',
            name='quarantine_duration',
        ),
        migrations.RemoveField(
            model_name='petrelocationrequirement',
            name='quarantine_required',
        ),
        migrations.RemoveField(
            model_name='petrelocationrequirement',
            name='restrictions',
        ),
        migrations.RemoveField(
            model_name='petrelocationrequirement',
            name='vaccination_requirements',
        ),
        migrations.RemoveField(
            model_name='visarequirement',
            name='details',
        ),
        migrations.RemoveField(
            model_name='visarequirement',
            name='is_mandatory',
        ),
        migrations.RemoveField(
            model_name='visarequirement',
            name='requirement',
        ),
        migrations.AddField(
            model_name='country',
            name='common_languages',
            field=models.ManyToManyField(related_name='countries', to='relocation_planner.language'),
        ),
        migrations.AddField(
            model_name='country',
            name='cost_of_living_index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='has_universal_healthcare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='pet_relocation_info_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='country',
            name='pet_relocation_requirements',
            field=models.ManyToManyField(related_name='countries', to='relocation_planner.petrelocationrequirement'),
        ),
        migrations.AddField(
            model_name='country',
            name='quality_of_life_index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='petrelocationrequirement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='petrelocationrequirement',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='petrelocationrequirement',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petrelocationrequirement',
            name='type',
            field=models.CharField(choices=[('VACCINATION', 'Vaccination'), ('QUARANTINE', 'Quarantine'), ('DOCUMENTATION', 'Documentation'), ('FEE', 'Fee')], default='vaccine', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visarequirement',
            name='description',
            field=models.TextField(default='justdefault'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visarequirement',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AnimalSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'animal species',
            },
        ),
        migrations.AddField(
            model_name='petrelocationrequirement',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relocation_planner.animalspecies'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('information_link', models.URLField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('requirements', models.ManyToManyField(to='relocation_planner.visarequirement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='country',
            name='visas',
            field=models.ManyToManyField(related_name='countries', to='relocation_planner.visa'),
        ),
        migrations.DeleteModel(
            name='CitizenshipProcess',
        ),
        migrations.DeleteModel(
            name='CostOfLiving',
        ),
        migrations.DeleteModel(
            name='EditHistory',
        ),
        migrations.DeleteModel(
            name='HealthcareInfo',
        ),
        migrations.DeleteModel(
            name='PropertyCost',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RelocationProcess',
        ),
        migrations.DeleteModel(
            name='ResourceLink',
        ),
        migrations.DeleteModel(
            name='UserExperience',
        ),
        migrations.DeleteModel(
            name='VisaType',
        ),
    ]
