# Generated by Django 5.1.3 on 2024-11-21 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relocation_planner', '0002_remove_costofliving_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='visas',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='requirements',
        ),
        migrations.AddField(
            model_name='visa',
            name='country',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='visa_list', to='relocation_planner.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visarequirement',
            name='visa',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_list', to='relocation_planner.visa'),
            preserve_default=False,
        ),
    ]
