# Generated by Django 5.1.3 on 2024-11-27 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relocation_planner', '0003_remove_country_visas_remove_visa_requirements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='pet_relocation_requirements',
        ),
        migrations.AddField(
            model_name='petrelocationrequirement',
            name='country',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, related_name='pet_requirement_list', to='relocation_planner.country'),
            preserve_default=False,
        ),
    ]
