# Generated by Django 5.1.3 on 2024-11-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['name'], 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterModelOptions(
            name='politicaldata',
            options={'verbose_name_plural': 'Political Data'},
        ),
        migrations.RemoveField(
            model_name='politicaldata',
            name='democrat_percentage',
        ),
        migrations.RemoveField(
            model_name='politicaldata',
            name='republican_percentage',
        ),
        migrations.RemoveField(
            model_name='politicaldata',
            name='total_donations',
        ),
        migrations.AddField(
            model_name='business',
            name='parent_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='companies.business'),
        ),
        migrations.AddField(
            model_name='business',
            name='provides_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='provides_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='conservative_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='conservative_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='liberal_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='liberal_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='save_america_pac_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='product_providers', to='companies.productcategory'),
        ),
        migrations.AddField(
            model_name='business',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='service_providers', to='companies.servicecategory'),
        ),
    ]
