# Generated by Django 5.1.3 on 2024-11-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_productcategory_servicecategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editrequest',
            old_name='republican_percentage',
            new_name='conservative_percentage',
        ),
        migrations.RenameField(
            model_name='editrequest',
            old_name='democrat_percentage',
            new_name='liberal_percentage',
        ),
        migrations.RemoveField(
            model_name='editrequest',
            name='total_donations',
        ),
        migrations.AddField(
            model_name='editrequest',
            name='conservative_total_donations',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='liberal_total_donations',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='save_america_pac_donor',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='editrequest',
            name='supporting_links',
            field=models.TextField(blank=True),
        ),
    ]
