# Generated by Django 5.1.3 on 2024-11-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_republican_percentage_editrequest_conservative_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='products_to_add',
            field=models.ManyToManyField(blank=True, related_name='edit_requests_adding', to='companies.productcategory'),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='products_to_remove',
            field=models.ManyToManyField(blank=True, related_name='edit_requests_removing', to='companies.productcategory'),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='provides_products',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='provides_services',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='services_to_add',
            field=models.ManyToManyField(blank=True, related_name='edit_requests_adding', to='companies.servicecategory'),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='services_to_remove',
            field=models.ManyToManyField(blank=True, related_name='edit_requests_removing', to='companies.servicecategory'),
        ),
    ]
