# Generated by Django 5.1.3 on 2024-11-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_editrequest_products_to_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='companies.businesscategory'),
        ),
        migrations.AlterField(
            model_name='business',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, to='companies.location'),
        ),
    ]
