# Generated by Django 5.1.3 on 2024-11-10 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_business_categories_alter_business_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editrequest',
            options={'permissions': [('can_review_edits', 'Can review edit requests')]},
        ),
    ]
