# Generated by Django 5.1.3 on 2024-11-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_business_categories_delete_businesscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='locations',
            field=models.ManyToManyField(blank=True, to='companies.location'),
        ),
    ]
