# Generated by Django 5.1.3 on 2024-11-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_rename_description_productcategory_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='parent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
