# Generated by Django 5.1.3 on 2024-11-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_csvimportratelimit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['name'], 'permissions': [('can_import_business_csv', 'Can import business data via CSV')], 'verbose_name_plural': 'Businesses'},
        ),
    ]
