# Generated by Django 5.1.3 on 2024-11-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_alter_business_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editrequest',
            name='america_pac_donor',
        ),
        migrations.RemoveField(
            model_name='editrequest',
            name='conservative_percentage',
        ),
        migrations.RemoveField(
            model_name='editrequest',
            name='conservative_total_donations',
        ),
        migrations.RemoveField(
            model_name='editrequest',
            name='liberal_percentage',
        ),
        migrations.RemoveField(
            model_name='editrequest',
            name='liberal_total_donations',
        ),
        migrations.RemoveField(
            model_name='editrequest',
            name='save_america_pac_donor',
        ),
        migrations.RemoveField(
            model_name='editrequest',
            name='trump_donor',
        ),
        migrations.RemoveField(
            model_name='politicaldata',
            name='america_pac_donor',
        ),
        migrations.RemoveField(
            model_name='politicaldata',
            name='conservative_percentage',
        ),
        migrations.RemoveField(
            model_name='politicaldata',
            name='conservative_total_donations',
        ),
        migrations.RemoveField(
            model_name='politicaldata',
            name='liberal_percentage',
        ),
        migrations.RemoveField(
            model_name='politicaldata',
            name='liberal_total_donations',
        ),
        migrations.RemoveField(
            model_name='politicaldata',
            name='save_america_pac_donor',
        ),
        migrations.RemoveField(
            model_name='politicaldata',
            name='trump_donor',
        ),
        migrations.AddField(
            model_name='editrequest',
            name='affiliated_pac_america_pac_donor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='affiliated_pac_conservative_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='affiliated_pac_liberal_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='affiliated_pac_save_america_pac_donor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='affiliated_pac_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='ceo_america_pac_donor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='ceo_save_america_pac_donor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='ceo_trump_donor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='direct_america_pac_donor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='direct_conservative_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='direct_liberal_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='direct_save_america_pac_donor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='direct_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='affiliated_pac_america_pac_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='affiliated_pac_conservative_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='affiliated_pac_liberal_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='affiliated_pac_save_america_pac_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='affiliated_pac_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='ceo_america_pac_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='ceo_save_america_pac_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='ceo_trump_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='direct_america_pac_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='direct_conservative_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='direct_liberal_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='direct_save_america_pac_donor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politicaldata',
            name='direct_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
