# Generated by Django 5.1.3 on 2024-11-15 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_remove_editrequest_america_pac_donor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicaldata',
            name='data_source',
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='companies.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
