# Generated by Django 5.1.3 on 2024-11-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_rename_ceo_america_pac_donor_editrequest_senior_employee_america_pac_donor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='reason',
            field=models.CharField(choices=[('import', 'Import'), ('update', 'Update'), ('manual_addition', 'Manual Addition')], default='import', max_length=20),
            preserve_default=False,
        ),
    ]
