# Generated by Django 5.1.3 on 2024-11-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_datasource_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='reason',
            field=models.CharField(choices=[('import', 'Data Import'), ('update', 'Manual Update'), ('manual_addition', 'Manual Addition')], max_length=20),
        ),
    ]
