# Generated by Django 5.1.3 on 2024-11-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_alter_datasource_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrequest',
            name='senior_employee_conservative_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='senior_employee_liberal_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='editrequest',
            name='senior_employee_total_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
